PROMPT_REASON_AND_PLAN = (
    "You are a clinical retrieval planner building a pre-visit patient summary "
    "from a real EHR. The summary is built INCREMENTALLY by issuing search "
    "queries against vector stores of clinical notes and chest X-rays — each "
    "of your queries triggers a retrieval and the results are merged into the "
    "summary on the next turn.\n\n"
    "CURRENT SUMMARY (partially-filled template):\n{summary}\n\n"
    "PAST ACTIONS:\n{action_history}\n\n"
    "Pick ONE next action.\n\n"
    "Actions:\n"
    "- search_text: query EHR notes / structured data.\n"
    "- search_imaging: query chest-X-ray reports.\n"
    "- finish: stop when no high-value query remains.\n\n"
    "TWO QUERY MODES — every query you issue is EITHER one mode or the other,\n"
    "and the rules differ:\n\n"
    "--------------------------------------------------------------------\n"
    "MODE A — TOPIC query (breadth pass)\n"
    "  Covers one of these 8 canonical topics, AT MOST ONCE per session:\n"
    "    1. active_problems   — current diagnoses, active conditions\n"
    "    2. medications       — current medication list\n"
    "    3. allergies         — drug allergies and adverse reactions\n"
    "    4. labs              — recent lab results / vitals trends\n"
    "    5. recent_events     — recent admissions, ED visits, clinical events\n"
    "    6. procedures        — past procedures and surgical history\n"
    "    7. imaging           — chest X-ray reports (use search_imaging)\n"
    "    8. social_history    — functional status, code status, social context\n\n"
    "  Tag the query with `mode=topic; topic=<one of the 8>` in `thought`.\n"
    "  Rephrasing a past topic query (adding adjectives, narrowing terms,\n"
    "  listing extra fields) counts as a REPEAT and is forbidden:\n"
    "    BAD pair (same topic, both topic-mode):\n"
    "      \"laboratory results\"\n"
    "      \"recent labs including electrolytes, creatinine, BUN\"\n"
    "    BAD pair:\n"
    "      \"social history and functional status\"\n"
    "      \"social history, living situation, caregiver support, functional status\"\n\n"
    "--------------------------------------------------------------------\n"
    "MODE B — DRILLDOWN query (depth pass)\n"
    "  Investigates a SPECIFIC ENTITY that already appears verbatim in\n"
    "  CURRENT SUMMARY — a named diagnosis, medication, procedure, lab,\n"
    "  imaging finding, or event. The query MUST mention that entity by\n"
    "  name (or a closely-related medical term).\n\n"
    "  When to drill down: after the breadth pass surfaces something that\n"
    "  is clinically high-stakes, longitudinal, or under-specified, AND\n"
    "  another retrieval is plausibly going to add useful information\n"
    "  (history, trend, dose, indication, complications, last-done date).\n\n"
    "  Tag the query with `mode=drilldown; entity=<the named thing>` in\n"
    "  `thought`. The entity MUST appear in CURRENT SUMMARY.\n\n"
    "  GOOD drilldown examples:\n"
    "    after summary lists \"chronic kidney disease\":\n"
    "      \"creatinine and GFR trend, dialysis status\"\n"
    "      thought: mode=drilldown; entity=chronic kidney disease\n"
    "    after summary lists \"NSTEMI\":\n"
    "      \"history of myocardial infarction, prior PCI or CABG\"\n"
    "      thought: mode=drilldown; entity=NSTEMI\n"
    "    after summary lists \"warfarin\":\n"
    "      \"warfarin indication, target INR, last INR value\"\n"
    "      thought: mode=drilldown; entity=warfarin\n\n"
    "  DRILLDOWN constraints:\n"
    "  - The named entity MUST be present in CURRENT SUMMARY. Don't drill\n"
    "    on something you only suspect or that's only in your prior thought.\n"
    "  - Max 3 drilldowns per session — pick the most clinically significant.\n"
    "  - You may NOT drill down on an entity twice in one session.\n"
    "  - A drilldown is NOT a way to retry a failed topic query with more\n"
    "    words; if you didn't name a specific entity from the summary, it's\n"
    "    actually a topic query and the topic rules apply.\n\n"
    "--------------------------------------------------------------------\n"
    "PROCEDURE for picking the next action:\n"
    "  1. Walk through PAST ACTIONS. For each entry note its mode and tag\n"
    "     (topic=X or entity=Y).\n"
    "  2. If any canonical topic is uncovered AND clinically relevant,\n"
    "     issue a TOPIC query on it.\n"
    "  3. Else if a high-stakes entity in CURRENT SUMMARY is under-specified\n"
    "     AND has not been drilled on yet AND you have <3 drilldowns so far,\n"
    "     issue a DRILLDOWN query on it.\n"
    "  4. Else return `finish`.\n\n"
    "FIRST-TURN POLICY (PAST ACTIONS is empty):\n"
    "- DO NOT finish. Start with a TOPIC query on `active_problems`,\n"
    "  e.g. query: \"active problems and current diagnoses\".\n\n"
    "Rules:\n"
    "- One action and ONE focused query per turn.\n"
    "- Do NOT put time expressions in the query text. Control time via `allowed_years`.\n"
    "- Default windows: labs/meds 1-2y, chronic conditions 1-3y, imaging/procedures 2-5y.\n"
    "- Omit `allowed_years` only for inherently historical queries (initial diagnosis date,\n"
    "  past surgical history, genetic conditions).\n\n"
    "Return JSON only:\n"
    '{{"action": "search_text|search_imaging|finish", "query": "...", '
    '"allowed_years": <int or omit>, '
    '"thought": "mode=topic|drilldown; topic=<one of 8> OR entity=<from summary>; <brief reason>"}}'
)


PROMPT_UPDATE_TEMPLATE = (
    "NEWLY RETRIEVED DOCUMENTS:\n{retrieved_docs_str}\n\n"
    "CURRENT SUMMARY (JSON):\n{summary}\n\n"
    "Extract ONLY new clinical facts from the documents that are not already in the summary,\n"
    "and return them as a JSON patch grouped by section: active_problems, recent_events,\n"
    "medications, allergies, key_results, procedures, pending_items.\n\n"
    "Rules:\n"
    "- Do not rewrite, modify, or duplicate existing entries.\n"
    "- Place each fact in the correct section (active_problems = diagnoses; key_results = labs/vitals/imaging results).\n"
    "- Every entry MUST have its primary content field populated:\n"
    "    active_problems → 'problem'   |  medications  → 'name'\n"
    "    recent_events   → 'event'     |  allergies    → 'substance'\n"
    "    key_results     → 'test'      |  procedures   → 'procedure'\n"
    "    pending_items   → 'item'\n"
    "  An entry with only 'evidence' and a blank primary field is INVALID — omit it entirely.\n"
    '- Each new fact MUST include "evidence" with "source_id" and "date".\n'
    "- Use only explicit info from the documents — no inference. If a document mentions a\n"
    "  section topic (e.g. 'discharge medications') but lists no concrete items, do not\n"
    "  emit a placeholder entry — return nothing for that section.\n"
    "- If no new facts: return exactly {{}}.\n"
    "- Output strictly valid JSON, no commentary, no markdown."
)


START_CHAT_PROMPT = (
    "PATIENT CLINICAL SUMMARY:\n{summary}\n\n"
    "Answer the user using only the retrieved documents, the live conversation transcript,\n"
    "and the clinical summary. Prefer the transcript when it directly answers the question;\n"
    "otherwise rely on retrieved documents. Cite each claim with its Document ID and date."
)


PROMPT_RAG_RETRIEVAL = (
    "PATIENT CLINICAL SUMMARY:\n{summary}\n\n"
    "LIVE CONVERSATION TRANSCRIPT:\n{full_transcript}\n\n"
    "CHAT HISTORY:\n{chat_history}\n\n"
    "LATEST USER QUESTION:\n{question}\n\n"
    "Form ONE standalone medical search query optimised for vector retrieval.\n"
    "- Self-contained (no references to chat history).\n"
    "- Concise medical terminology.\n"
    "- No natural-language time expressions (use `allowed_years`).\n\n"
    "Actions: search_text (preferred) or search_imaging (only if imaging is essential).\n"
    "Default windows: labs/meds 1-2y, chronic 1-3y, imaging/procedures 2-5y.\n"
    "Omit `allowed_years` only for inherently historical queries.\n\n"
    "Return JSON only:\n"
    '{{"action": "search_text|search_imaging", "query": "...", "allowed_years": <int or omit>}}'
)


PROMPT_RAG = (
    "LIVE CONVERSATION TRANSCRIPT:\n{full_transcript}\n\n"
    "USER QUESTION: {question}\n\n"
    "RETRIEVED DOCUMENTS:\n{retrieved_docs_str}"
)


PROMPT_SUMMARIZE_TRANSCRIPTION = (
    "TRANSCRIPT:\n{full_text}\n\n"
    "CONVERSATION SUMMARY:\n{conversation_summary}\n\n"
    "Update the conversation summary based on the transcript.\n"
    "- Add new information; refine existing fields when the transcript clarifies them.\n"
    "- Do not remove confirmed facts unless explicitly corrected.\n"
    '- Add unanswered clinician questions to "open_questions".\n'
    "- Do not invent values. Output strictly valid JSON only."
)


PROMPT_ALERTS = (
    "PATIENT SUMMARY:\n{summary}\n\n"
    "LIVE TRANSCRIPT:\n{full_transcript}\n\n"
    "CONVERSATION SUMMARY:\n{conversation_summary}\n\n"
    "You are a clinical safety assistant. Surface only ALERTS the clinician should be aware of right now —\n"
    "clinically significant connections between the live conversation and the patient's history.\n\n"
    "Examples:\n"
    "- Patient mentions chest pain; last troponin was over 6 months ago.\n"
    "- Patient describes a new OTC medication that may interact with an existing prescription.\n"
    "- Reported symptom contradicts an active diagnosis in the summary.\n\n"
    "Rules:\n"
    "- Only include alerts SUPPORTED by both the conversation and the summary.\n"
    "- 0–5 alerts. If nothing is alert-worthy, return {{\"alerts\": []}}.\n"
    "- Each alert: short title + one-line rationale + (optional) suggested action.\n\n"
    "Return JSON only:\n"
    '{{"alerts": [{{"title": "...", "rationale": "...", "suggested_action": "..."}}]}}'
)


PROMPT_SOAP_NOTE = (
    "PATIENT SUMMARY:\n{summary}\n\n"
    "VISIT TRANSCRIPT:\n{full_transcript}\n\n"
    "CONVERSATION SUMMARY:\n{conversation_summary}\n\n"
    "Write a concise SOAP note in markdown for this visit.\n\n"
    "S — Subjective: chief complaint, HPI, relevant ROS in the patient's words.\n"
    "O — Objective: vitals, exam findings, lab/imaging results discussed in the visit.\n"
    "A — Assessment: differential or working diagnosis, with brief reasoning.\n"
    "P — Plan: medications, orders, follow-up, patient instructions.\n\n"
    "Rules:\n"
    "- Use only information present in the transcript or summary.\n"
    "- Do not invent vitals, dosages, or follow-up dates.\n"
    "- Mark uncertain items with \"(to confirm)\".\n"
    "- Output markdown only — no preamble, no JSON, no code fences."
)
